version: '2.1'
services:
  influxdb:
    image: influxdb:1.1
    volumes:
      - influx-data:/var/lib/influxdb
    logging:
      driver: syslog
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: grafana/grafana:4.0.1
    logging:
      driver: syslog
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - grafana-variables-${ENV}.env

  brood:
    build: .
    logging:
      driver: syslog
    depends_on:
      - influxdb
    ports:
      - "4000:4000"
    expose:
      - "4000"
volumes:
  influx-data:
    driver: local
